### ISSUE TITLE
Failure loading nipype.

### ISSUE THREAD

**Issue by tsalo** [NBCLab/nbclab-env#3]
import nipype
Error message:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/nipype/__init__.py", line 77, in <module>
    from pipeline import Node, MapNode, JoinNode, Workflow
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/nipype/pipeline/__init__.py", line 8, in <module>
    from engine import Node, MapNode, JoinNode, Workflow
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 45, in <module>
    from ..interfaces.base import (traits, InputMultiPath, CommandLine,
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/nipype/interfaces/__init__.py", line 12, in <module>
    import fsl, spm, freesurfer, afni, ants, slicer, dipy, nipy, mrtrix, camino
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/nipype/interfaces/dipy/__init__.py", line 1, in <module>
    from .tracks import TrackDensityMap
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/nipype/interfaces/dipy/tracks.py", line 19, in <module>
    from dipy.tracking.utils import density_map
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/dipy/tracking/utils.py", line 45, in <module>
    from ._utils import *
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/dipy/tracking/_utils.py", line 14, in <module>
    from . import metrics
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/dipy/tracking/metrics.py", line 7, in <module>
    from scipy.interpolate import splprep, splev
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/scipy/interpolate/__init__.py", line 162, in <module>
    from .rbf import Rbf
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/scipy/interpolate/rbf.py", line 51, in <module>
    from scipy import linalg
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 157, in <module>
    from .misc import *
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from . import blas
  File "/home/applications/python/2.7.5/lib/python2.7/site-packages/scipy/linalg/blas.py", line 131, in <module>
    from scipy.linalg import _fblas
ImportError: libptf77blas.so.3: cannot open shared object file: No such file or directory
```

**Comment by tsalo** [comment]
Spoke with Dr. Mattfeld. It's because I was using Spyder, which was using a different version of Python. From now on, I will use iPython notebooks.
